#!/usr/bin/env python3
"""Configure the network of the NAO.

This script configures the network of the NAO based on the hardware IDs and the
team number. It then composes the configuration for the WLAN and wired network
based on the team number and the number of the NAO, and sets the hostname.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path
from subprocess import check_call, check_output
from typing import Any

TEAM_TOML = "/media/internal/team.toml"
HEAD_ID_SCRIPT = "/opt/aldebaran/bin/head_id"
WLAN_NETWORK_PATH = "/etc/systemd/network/20-wlan.network"
WIRED_NETWORK_PATH = "/etc/systemd/network/20-wired.network"
FALLBACK_NETWORK_PATH = "/etc/systemd/network/60-fallback.network"
FALLBACK_CONFIGURATION = """\
[Match]
Type=ether
Name=!veth*
KernelCommandLine=!nfsroot
KernelCommandLine=!ip

[Network]
DHCP=yes
Address=172.28.28.28/24

[DHCP]
UseMTU=yes
RouteMetric=10
ClientIdentifier=mac
"""
DEFAULT_TEAM_TOML = """\
team_number = 24

[[naos]]
hostname = "sam"
number = 20
body_id = "P0000073A03S84F00018"
head_id = "P0000074A03S84F00015"

[[naos]]
hostname = "moos"
number = 21
body_id = "P0000073A03S83I00012"
head_id = "P0000074A03S83I00027"

[[naos]]
hostname = "phineas"
number = 22
body_id = "P0000073B00S8C700011"
head_id = "P0000074A04S8C700011"

[[naos]]
hostname = "ferb"
number = 23
body_id = "P0000073A06S91300024"
head_id = "P0000074A04S91300023"

[[naos]]
hostname = "momo"
number = 24
body_id = "P0000073A09S98900028"
head_id = "P0000074A05S98900017"

[[naos]]
hostname = "appa"
number = 25
body_id = "P0000073A10S9BH00033"
head_id = "P0000074A06S9BH00015"

[[naos]]
hostname = "daphne"
number = 26
body_id = "P0000073A19S31C00026"
head_id = "P0000074A09S31C00026"

[[naos]]
hostname = "perry"
number = 27
body_id = "P0000073A06S8CP00020"
head_id = "P0000074A02S81F00020"

[[naos]]
hostname = "barbie"
number = 28
body_id = "P0000073A20S42L00016"
head_id = "P0000074A10S42L00016"

[[naos]]
hostname = "ken"
number = 29
body_id = "P0000073A20S42L00015"
head_id = "P0000074A10S42L00015"
"""


def load_configuration(path: Path | str) -> dict[str, Any]:
    """Load the configuration from the given path.

    Args:
        path: Path to the configuration file.

    Returns:
        The configuration

    """
    path = Path(path)

    if not path.exists():
        return tomllib.loads(DEFAULT_TEAM_TOML)

    with path.open("rb") as file:
        return tomllib.load(file)


def query_head_id() -> str:
    """Query the head ID of the NAO.

    Returns:
        The head ID of the NAO.

    """
    command = HEAD_ID_SCRIPT.split()
    output = check_output(command, encoding="UTF-8")
    return output.strip()


def find_nao_with_head_id(
    configuration: dict[str, Any],
    head_id: str,
) -> dict[str, Any]:
    """Find the NAO with the given head ID in the configuration.

    Args:
        configuration: The configuration.
        head_id: The head ID of the NAO.

    Returns:
        The NAO with the given head ID.

    """
    try:
        return next(x for x in configuration["naos"] if x["head_id"] == head_id)
    except StopIteration as error:
        msg = f"Could not find NAO with head_id {head_id}"
        raise ValueError(msg) from error


def compose_wlan_network(nao: dict[str, Any], team_number: int) -> str:
    """Compose the configuration for the WLAN network.

    Args:
        nao: The NAO.
        team_number: The team number.

    Returns:
        The configuration for the WLAN network.

    """
    return f"""\
[Match]
Name=wlan*

[Network]
Address=10.0.{team_number}.{nao["number"]}/16

[Route]
Gateway=0.0.0.0
"""


def compose_wired_network(nao: dict[str, Any], team_number: int) -> str:
    """Compose the configuration for the wired network.

    Args:
        nao: The NAO.
        team_number: The team number.

    Returns:
        The configuration for the wired network.

    """
    return f"""\
[Match]
Name=en* eth*

[Network]
Address=10.1.{team_number}.{nao["number"]}/16

[Route]
Gateway=10.1.24.1
Destination=10.2.24.0/24

[Route]
Gateway=10.1.24.1
Destination=10.4.24.0/24
"""


def write_to_file(path: str | Path, content: str) -> None:
    """Write the content to the file at the given path.

    Args:
        path: Path to the file.
        content: Content to write.

    """
    path = Path(path)
    with path.open("w") as file:
        file.write(content)


def set_hostname(hostname: str) -> None:
    """Set the hostname of the NAO.

    Args:
        hostname: The hostname.

    """
    check_call(["/usr/bin/hostnamectl", "set-hostname", hostname])


if __name__ == "__main__":
    configuration = load_configuration(TEAM_TOML)
    head_id = query_head_id()
    try:
        nao = find_nao_with_head_id(configuration, head_id)
    except ValueError as error:
        print(error)
        write_to_file(FALLBACK_NETWORK_PATH, FALLBACK_CONFIGURATION)
        sys.exit(1)

    wlan_configuration = compose_wlan_network(
        nao,
        configuration["team_number"],
    )
    wired_configuration = compose_wired_network(
        nao,
        configuration["team_number"],
    )

    write_to_file(WLAN_NETWORK_PATH, wlan_configuration)
    write_to_file(WIRED_NETWORK_PATH, wired_configuration)
    set_hostname(nao["hostname"])
